export const productList = [
  {
    title: "bowl",
    description: "bowl",
    category: "bowl",
    price: 34.99,
    material: ["clay"],
    color: "black",
    image: "image",
  },
  {
    title: "cup",
    description: "cup",
    category: "cups",
    price: 34.99,
    material: ["clay"],
    color: "white",
    image: "image",
  },
  {
    title: "pitcher",
    description: "pitcher",
    category: "pitchers",
    price: 34.99,
    material: ["clay"],
    color: "green",
    image: "image",
  },
  {
    title: "plate",
    description: "plate",
    category: "plates",
    price: 34.99,
    material: ["clay"],
    color: "gray",
    image: "image",
  },
  {
    title: "vase",
    description: "vase",
    category: "vases",
    price: 34.99,
    material: ["clay"],
    color: "yellow",
    image: "image",
  },
];
